name = "brazilianwax-ing-v1"
compatibility_date = "2026-06-30"
workers_dev = false
preview_urls = false

[[routes]]
pattern = "brazilianwax.ing"
custom_domain = true

[[routes]]
pattern = "www.brazilianwax.ing"
custom_domain = true

[assets]
directory = "./dist"
html_handling = "auto-trailing-slash"
